apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziacka-knizka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziacka-knizka
  template:
    metadata:
      labels:
        app: ziacka-knizka
    spec:
      containers:
        - name: cms-app
          image: pepega2323/ziacka-knizka:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: cms-db
            - name: DB_DATABASE
              value: cms
            - name: DB_USER
              value: cms
            - name: DB_PASSWORD
              value: Heslo123
            - name: SMTP_HOST
              value: fake-smtp
            - name: SMTP_PORT
              value: "25"
---
apiVersion: v1
kind: Service
metadata:
  name: ziacka-knizka
spec:
  selector:
    app: ziacka-knizka
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer
