apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-mariadb
  template:
    metadata:
      labels:
        app: cms-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: "cms"
            - name: MARIADB_USER
              value: "cms"
            - name: MARIADB_PASSWORD
              value: "Heslo123"
            - name: MARIADB_ROOT_PASSWORD
              value: "Heslo123"
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/init_cms.sql
              subPath: init_cms.sql
      volumes:
        - name: initdb
          configMap:
            name: cms-db-init
---
apiVersion: v1
kind: Service
metadata:
  name: cms-db
spec:
  selector:
    app: cms-mariadb
  ports:
    - port: 3306
      targetPort: 3306
